"""empty message

Revision ID: 1d329e436ecc
Revises: 16b6f57097d5
Create Date: 2020-09-28 00:13:18.252585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d329e436ecc'
down_revision = '16b6f57097d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendee', sa.Column('order_id', sa.TEXT(), nullable=False))
    op.add_column('attendee', sa.Column('ticket_type', sa.TEXT(), nullable=True))
    op.add_column('attendee', sa.Column('type', sa.TEXT(), nullable=True))
    op.create_unique_constraint(None, 'attendee', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendee', type_='unique')
    op.drop_column('attendee', 'type')
    op.drop_column('attendee', 'ticket_type')
    op.drop_column('attendee', 'order_id')
    # ### end Alembic commands ###
