"""empty message

Revision ID: c974f7011300
Revises: 
Create Date: 2020-09-13 17:55:04.637717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c974f7011300'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendee',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('fullname', sa.TEXT(), nullable=False),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('twitter_id', sa.TEXT(), nullable=True),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_attendee_booking_id'), 'attendee', ['booking_id'], unique=True)
    op.create_index(op.f('ix_attendee_email'), 'attendee', ['email'], unique=False)
    op.create_index(op.f('ix_attendee_username'), 'attendee', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendee_username'), table_name='attendee')
    op.drop_index(op.f('ix_attendee_email'), table_name='attendee')
    op.drop_index(op.f('ix_attendee_booking_id'), table_name='attendee')
    op.drop_table('attendee')
    # ### end Alembic commands ###
